### ISSUE TITLE
Reorder minimize and maximize buttons

### ISSUE THREAD

**Issue by iKlsR** [andresilvasantos/beatwhale#3]
The order of these should flow as the default in all WMs. Minimize, maximize then close as opposed to maximize first.

**Comment by andresilvasantos** [comment]
You are not the first telling me that and I know in windows the way you described it's what they use, but in OS X it's different (http://cdn.osxdaily.com/wp-content/uploads/2014/10/green-maximize-zoom-button-os-x-yosemite.png)

The way I think they see it in OS X is like the semaphore lights, going from the safe one to the danger one. Maximize has no problem at all, minimize is a bit more problematic since it hides completely the window and finally close the application, the most dangerous of the three.

What do you think?

**Comment by iKlsR** [comment]
@andresilvasantos Oh, I can count on one hand the amount of times I've used a mac so can't recall that. It's a bit weird for other OS users I would think since this is the norm. I would probably detect platform and change color/functionality with that but with that said it seems rather trivial now.

**Comment by andresilvasantos** [comment]
Fixed in version 0.8.0.
I'll close this issue now.
